# Generated by Django 4.2 on 2025-09-05 23:00

import tinymce
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', tinymce.models.HTMLField(blank=True, help_text='Content that will be displayed in the info section of the website', null=True)),
            ],
            options={
                'verbose_name_plural': 'Info / About',
            },
        ),
        migrations.CreateModel(
            name='MarqueeText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, help_text='Content that is populated in the marquee', max_length=500, null=True)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether or not the content will show on the marquee')),
            ],
            options={
                'verbose_name_plural': 'Marquee Text',
            },
        ),
    ]
