# Generated by Django 4.2 on 2025-09-05 18:12

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('start_time', models.IntegerField(choices=[(0, '12 am'), (1, '1 am'), (2, '2 am'), (3, '3 am'), (4, '4 am'), (5, '5 am'), (6, '6 am'), (7, '7 am'), (8, '8 am'), (9, '9 am'), (10, '10 am'), (11, '11am'), (12, '12 pm'), (13, '1 pm'), (14, '2 pm'), (15, '3 pm'), (16, '4 pm'), (17, '5 pm'), (18, '6 pm'), (19, '7 pm'), (20, '8 pm'), (21, '9 pm'), (22, '10 pm'), (23, '11 pm')])),
                ('duration', models.IntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=1)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('end_date_time', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('show_image', models.ImageField(blank=True, help_text="The show's image that will be displayed on the site while the show is live.", max_length=500, upload_to='shows/images/')),
                ('show_flyer', models.ImageField(blank=True, help_text="The show's flyer that will be used on the schedule page and for social media.", max_length=500, upload_to='shows/images/')),
                ('pre_recorded_show', models.FileField(blank=True, help_text='Optional upload field for pre-recorded shows. Files MUST be in MP3 format.', max_length=500, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/sumle/Code/Sites/itr_upgrade/introtorhythm_backend')), upload_to='uploads/scheduler/')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time')},
            },
        ),
    ]
