# Generated by Django 4.2 on 2026-03-23 17:43

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='pre_recorded_show',
            field=models.FileField(blank=True, help_text='Optional upload field for pre-recorded shows. Files MUST be in MP3 format.', max_length=500, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/seanpierce/www/staging.introtorhythm.com/introtorhythm_backend')), upload_to='uploads/scheduler/'),
        ),
    ]
